//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorJsonFormTester.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorJsonFormTester.Core.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional payloads.
        /// </summary>
        internal static string AdditionalPayloads_label {
            get {
                return ResourceManager.GetString("AdditionalPayloads_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient temperature.
        /// </summary>
        internal static string AmbientTemperature_label {
            get {
                return ResourceManager.GetString("AmbientTemperature_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babel fish dictionary.
        /// </summary>
        internal static string BabelFishDictionary_label {
            get {
                return ResourceManager.GetString("BabelFishDictionary_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable telemetry.
        /// </summary>
        internal static string EnableTelemetry_label {
            get {
                return ResourceManager.GetString("EnableTelemetry_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine count.
        /// </summary>
        internal static string EngineCount_label {
            get {
                return ResourceManager.GetString("EngineCount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight duration.
        /// </summary>
        internal static string FlightDuration_label {
            get {
                return ResourceManager.GetString("FlightDuration_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight start.
        /// </summary>
        internal static string FlightStart_label {
            get {
                return ResourceManager.GetString("FlightStart_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string Fuel_label {
            get {
                return ResourceManager.GetString("Fuel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headlight brightness.
        /// </summary>
        internal static string HeadlightBrightness_label {
            get {
                return ResourceManager.GetString("HeadlightBrightness_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImprobabilityDriveFlux.
        /// </summary>
        internal static string ImprobabilityDriveFlux_label {
            get {
                return ResourceManager.GetString("ImprobabilityDriveFlux_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch coordinates.
        /// </summary>
        internal static string LaunchCoordinates_label {
            get {
                return ResourceManager.GetString("LaunchCoordinates_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main payload.
        /// </summary>
        internal static string MainPayload_label {
            get {
                return ResourceManager.GetString("MainPayload_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_label {
            get {
                return ResourceManager.GetString("Message_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionDataPath.
        /// </summary>
        internal static string MissionDataPath_label {
            get {
                return ResourceManager.GetString("MissionDataPath_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission targets.
        /// </summary>
        internal static string MissionTargets_label {
            get {
                return ResourceManager.GetString("MissionTargets_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name_label {
            get {
                return ResourceManager.GetString("Name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status_label {
            get {
                return ResourceManager.GetString("Status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        internal static string Storage_label {
            get {
                return ResourceManager.GetString("Storage_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight_label {
            get {
                return ResourceManager.GetString("Weight_label", resourceCulture);
            }
        }
    }
}
